---
title: "Le premier chargement"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Le premier chargement}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(didoscalim)
```

# Comment utiliser didoscalim

## Créer le dataset

```{r}
dataset <- create_dataset(
  title = "mon dataset de test didoscalim",
  description = "test",
  topic = "Transports",
  frequency = "unknown",
  temporal_coverage_start = "2020-01-01",
  temporal_coverage_end = "2020-12-31"
)
```

## créer un datafile

```{r}
create_datafile(
  dataset = dataset,
  file_name = "augmente.csv",
  title = "Données de consommation et de points de livraison d'énergie à la maille IRIS – chaleur et froid – année 2020",
  description = paste0("Consommations annuelles et nombre de points de livraison de gaz naturel, par secteur d'activité ",
                          "(agriculture, industrie, tertiaire, résidentiel et non affecté) ou selon le code NAF à 2 niveaux ",
                          "selon les cas, à la maille IRIS"),
  temporal_coverage_start = "2020-01-01",
  temporal_coverage_end = "2020-12-31"
)
```
## ajouter des fichiers annexes

```{r}
add_attachment(
    dataset = dataset,
    file_name = 'annexe.txt',
    title = "Liste des variables - chaleur et froid",
    description = "Détail des variables - fichiers chaleur et froid"
)
```
